Hex Input Options
pstirparo/utils pull request #2
Opened 2019-07-28 16:53 UTC by amm3

For consideration, this commit does two things:
  * Automatically/always remove spaces in hex input
  * Add option (`-r, --revhex`) to reverse (by byte) hex input.  Useful when copy/pasting little-endian input.

2019-08-02 16:41 UTC, pstirparo requested changes
Thanks for the contribution, please find below some comments.

2019-08-02 16:41 UTC, pstirparo commented on epochalypse.py
Remove newline

2019-08-02 16:41 UTC, pstirparo commented on epochalypse.py
> +      hex_text = hex_text.decode('hex')[::-1].encode('hex')
That's python2, this new version of the script is python3 and decode method on string does not work.

2019-08-02 16:55 UTC, amm3 commented
Good point, @pstirparo.  The only method I'm aware of that's compatible with both is to use binascii.  Py3 doesn't support `decode('hex')` and Py2 doesn't support `bytes.fromhex()`.  Does this work for you?

2019-09-10 12:18 UTC, amm3 commented
Have you had a chance to review my changes, @pstirparo. Github still shows "changes requested", but I believe I've addressed all your concerns.

2020-05-03 14:50 UTC, pstirparo requested changes
This was long due, my apologies.
The code is working, just few "cosmetics" comments to be consistent with the code and then I will merge it.
Thanks again.

2020-05-03 14:50 UTC, pstirparo commented on epochalypse.py
> +
Delete new line

2020-05-03 14:50 UTC, pstirparo commented on epochalypse.py
> +  parser.add_argument("-r", "--revhex", action="store_true", default=False,
Change double quote to single quote for consistency. Also in the line below.

2020-05-03 14:50 UTC, pstirparo commented on epochalypse.py
> +      hex_text = binascii.hexlify( binascii.unhexlify( hex_text )[::-1] ).decode()
Remove space within hexlify(), after the open brackets and before the closing ones

2020-05-13 09:49 UTC, merged

2020-05-13 09:50 UTC, pstirparo commented
Thanks a lot for the contribution Adam :)